#define the port number
server:
   port: 8088

# Add application name
spring:
    application:
         name: bowling-info-service

PATCH_METHOD_TIMEOUT: 120000

#Enable H2 database Console
spring.h2.console.enabled: true

#API URLS
player.info:
          check-palayer-exists: http://player-info-service/api/internal/player-info/{player-id}/exists
